FROM node:16

WORKDIR /app

ADD package.json .
ADD yarn.lock .

RUN yarn

ADD . .

WORKDIR /app/packages/prop-house-communities

RUN yarn

RUN yarn build

WORKDIR /app/packages/prop-house-wrapper

RUN yarn

RUN yarn build

WORKDIR /app/packages/prop-house-backend

RUN yarn

RUN yarn build

CMD [ "node", "dist/main.js" ]
