FROM node:16

WORKDIR /app/packages/prop-house-nounish-contracts

ADD . .

RUN yarn build

WORKDIR /app

ADD package.json .
ADD yarn.lock .

RUN yarn

ADD . .

WORKDIR /app/packages/prop-house-backend

RUN yarn

RUN yarn build

CMD [ "node", "dist/main.js" ]
