FROM node:16 AS builder
WORKDIR /app

ADD package.json .
ADD yarn.lock .

ADD . .


RUN yarn

RUN yarn build

WORKDIR /app/packages/@prophouse/communities

RUN yarn

RUN yarn build

WORKDIR /app/packages/prop-house-card-renderer

RUN yarn

RUN yarn build


FROM ghcr.io/puppeteer/puppeteer:16.1.0

COPY --from=builder /app .

RUN mkdir /tmp/phcache

CMD [ "node", "build/index.js" ]
