FROM node:16

WORKDIR /app

ADD package.json .
ADD yarn.lock .

ADD . .

RUN yarn

RUN yarn build

WORKDIR /app/packages/prop-house-communities

RUN yarn

RUN yarn build

WORKDIR /app/packages/prop-house-card-renderer

RUN yarn

RUN yarn build

RUN mkdir /tmp/phcache

CMD [ "node", "build/index.js" ]
