[context.deploy-preview.environment]
    REACT_APP_NODE_ENV = "development"

[context.branch-deploy.environment]
    REACT_APP_NODE_ENV = "development"
    
[context.offchain]
    REACT_APP_NODE_ENV = "production"

[context.production.environment]
    REACT_APP_NODE_ENV = "production"
