[context.deploy-preview.environment]
    REACT_APP_NODE_ENV = "development"

[context.branch-deploy.environment]
    REACT_APP_NODE_ENV = "development"

[context.nethermind.environment]
    REACT_APP_NODE_ENV = "production"
    REACT_APP_PROD_BACKEND_URI = "http://nethermind.backend.prop.house"

[context.production.environment]
    REACT_APP_NODE_ENV = "production"