export const NounImage = {
  Banana: { src: '/heads/banana.png', alt: 'banana' },
  Blackhole: { src: '/heads/blackhole.png', alt: 'blackhole' },
  Boxingglove: { src: '/heads/boxingglove.png', alt: 'boxingglove' },
  Calculator: { src: '/heads/calculator.png', alt: 'calculator' },
  Camera: { src: '/heads/camera.png', alt: 'camera' },
  Chart: { src: '/heads/chart.png', alt: 'chart' },
  Computer: { src: '/heads/computer.png', alt: 'computer' },
  Cone: { src: '/heads/cone.png', alt: 'cone' },
  Crown: { src: '/heads/crown.png', alt: 'crown' },
  Earth: { src: '/heads/earth.png', alt: 'earth' },
  Glasses: { src: '/heads/glasses.png', alt: 'glasses' },
  Hardhat: { src: '/heads/hardhat.png', alt: 'hardhat' },
  Heart: { src: '/heads/heart.png', alt: 'heart' },
  House: { src: '/heads/house.png', alt: 'house' },
  Laptop: { src: '/heads/laptop.png', alt: 'laptop' },
  Thumbsup: { src: '/heads/thumbsup.png', alt: 'thumbsup' },
  Trashcan: { src: '/heads/trashcan.png', alt: 'trashcan' },
  Wallet: { src: '/heads/wallet.png', alt: 'wallet' },
  Whale: { src: '/heads/whale.png', alt: 'whale' },
};
