services:
  db:
    image: bitnami/postgresql:11.14.0-debian-10-r28
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
     - postgres-data:/bitnami/postgresql
     - ./db-init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8080:8080

  simnet:
    image: ghcr.io/foundry-rs/foundry:latest
    entrypoint: anvil --fork-url https://mainnet.infura.io/v3/$REACT_APP_INFURA_PROJECT_ID
    volumes:
      - "../../scripts:/scripts"
    ports:
      - "8545:8545"
    env_file:
      - .env

volumes:
   postgres-data:
     driver: local

